package GUI;

import models.EO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class addAB extends javax.swing.JFrame {
    EO Baju;

    /**
     * Creates new form Tambah
     */
    public addAB() throws ClassNotFoundException, SQLException {
        Baju = new EO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formMerk = new javax.swing.JTextField();
        formTR = new javax.swing.JTextField();
        formHarga = new javax.swing.JTextField();
        addDatas = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        formMerk.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        formMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMerkActionPerformed(evt);
            }
        });
        getContentPane().add(formMerk);
        formMerk.setBounds(210, 90, 410, 30);

        formTR.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        formTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTRActionPerformed(evt);
            }
        });
        getContentPane().add(formTR);
        formTR.setBounds(210, 140, 410, 40);

        formHarga.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        formHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formHargaActionPerformed(evt);
            }
        });
        getContentPane().add(formHarga);
        formHarga.setBounds(210, 190, 410, 40);

        addDatas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        addDatas.setText("Tambah");
        addDatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDatasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addDatasMouseEntered(evt);
            }
        });
        addDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDatasActionPerformed(evt);
            }
        });
        getContentPane().add(addDatas);
        addDatas.setBounds(30, 280, 130, 40);

        cancel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(500, 280, 130, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/TAMBAH.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 660, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMerkActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void formTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formTRActionPerformed

    private void formHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formHargaActionPerformed

    private void addDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDatasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDatasActionPerformed

    private void addDatasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDatasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addDatasMouseEntered

    private void addDatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDatasMouseClicked
        try{
            String hb = formMerk.getText();
            String jb = formTR.getText();
            int kb = Integer.parseInt(formHarga.getText());

            Baju.insert(hb, jb, kb);

            JOptionPane.showMessageDialog(null, "BERHASIL !");

            new Menu().setVisible(true);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tolong Masukan Data Yang Valid !");
            try {
                new addAB().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(addAB.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(addAB.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_addDatasMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        try {
            new Menu().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addAB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addAB.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDatas;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField formHarga;
    private javax.swing.JTextField formMerk;
    private javax.swing.JTextField formTR;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
