/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author 
 */
import models.EO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class upAB extends javax.swing.JFrame {
    EO eo1;

    /**
     * Creates new form addAB
     */
    public upAB() throws ClassNotFoundException, SQLException {
        eo1 = new EO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formMerk = new javax.swing.JTextField();
        formTR = new javax.swing.JTextField();
        formHarga = new javax.swing.JTextField();
        upData = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        formMerk.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        formMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMerkActionPerformed(evt);
            }
        });
        getContentPane().add(formMerk);
        formMerk.setBounds(210, 110, 420, 30);

        formTR.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        formTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formTRActionPerformed(evt);
            }
        });
        getContentPane().add(formTR);
        formTR.setBounds(210, 160, 420, 40);

        formHarga.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        formHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formHargaActionPerformed(evt);
            }
        });
        getContentPane().add(formHarga);
        formHarga.setBounds(210, 210, 420, 40);

        upData.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        upData.setText("Ubah");
        upData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upDataMouseEntered(evt);
            }
        });
        upData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDataActionPerformed(evt);
            }
        });
        getContentPane().add(upData);
        upData.setBounds(30, 300, 120, 50);

        cancel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(510, 300, 130, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/UPDATE.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 670, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMerkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMerkActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void formTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formTRActionPerformed

    private void formHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formHargaActionPerformed

    private void upDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upDataActionPerformed

    private void upDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_upDataMouseEntered

    private void upDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDataMouseClicked
        try {  
            int ib = Integer.parseInt(JOptionPane.showInputDialog("Masukan ID : "));
            String hb = formMerk.getText();
            String jb = formTR.getText();
            int kb = Integer.parseInt(formHarga.getText());
                
            eo1.update(ib, hb, jb, kb);
                
            JOptionPane.showMessageDialog(null, "UBAH DATA BERHASIL");
            
            new Menu().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "UBAH DATA GAGAL");
            try {
                new upAB().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(upAB.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(upAB.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_upDataMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        try {
            new Menu().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addAB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addAB.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField formHarga;
    private javax.swing.JTextField formMerk;
    private javax.swing.JTextField formTR;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton upData;
    // End of variables declaration//GEN-END:variables
}
